import type { Metadata } from "next";
import { User } from "lucide-react";
import { Toaster } from "@/components/ui/sonner";
import "@/app/globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import { auth } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (session) {
    return (
      <>
        <div>
          <div className="flex items-center justify-end p-4 bg-foreground text-white">
            <div className="flex items-center space-x-4">
              <User className="w-6 h-6" />
            </div>
          </div>
        </div>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full">
            <SidebarTrigger />
            {children}
            <Toaster />
          </main>
        </SidebarProvider>
      </>
    );
  }
  return (
    <html lang="en">
      <body className="antialiased">
        <main>NOT AUTHORIZED</main>
        <Toaster />
      </body>
    </html>
  );
}
